"""empty message

Revision ID: 5fddd039e326
Revises: 389f6e0bac4a
Create Date: 2023-11-01 22:40:03.154074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fddd039e326'
down_revision = '389f6e0bac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
