"""empty message

Revision ID: 8b10e6d41c84
Revises: 0b1d3fdcd429
Create Date: 2023-11-03 22:46:13.003605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b10e6d41c84'
down_revision = '0b1d3fdcd429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=250), nullable=True))
        batch_op.alter_column('height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('homeworld')
        batch_op.drop_column('mass')
        batch_op.drop_column('species')

    # ### end Alembic commands ###
